lib/inc/cpp-pcp-client/connector/connection.hpp
lib/src/connector/connection.cc

Here we adjust the reconnect delay with a random interval between -500
and 500 milliseconds. This will give us some grace when a broker goes
down, since all clients will no longer attempt to reconnect at exactly
the same time.
As a side effect all durations in Connection have been changed to
milliseconds from microseconds and seconds. Changing the reconnect sleep
to miliseconds gives us more precision, and changing the rest keeps
everything uniform.

(PCP-31) Randomise reconnect timeout

---

lib/inc/cpp-pcp-client/connector/connection.hpp
lib/inc/cpp-pcp-client/connector/connector.hpp
lib/inc/cpp-pcp-client/connector/timings.hpp
lib/inc/cpp-pcp-client/util/chrono.hpp
lib/inc/cpp-pcp-client/util/thread.hpp
lib/src/connector/connection.cc
lib/src/connector/connector.cc
lib/src/connector/timings.cc

Here we add two header files to encapsulate which threading, locking and
chrono libraries we use. Due to us not currently having working
std::thread available on AIX, we make the switch to boost::thread. In
the future we can switch back to using the standard libraries by
replacing boost:: with std:: in thread.hpp and chrono.hpp.

(PCP-53) Port cpp-pcp-client to boost::thread

---

lib/inc/cpp-pcp-client/util/thread.hpp

Boost.Thread's shared_mutex implementation generates a strict-aliasing
warning on Windows with mingw. Suppress those warnings so we can compile.

(maint) Fix compiling pxp-agent on Windows

---

lib/inc/cpp-pcp-client/protocol/schemas.hpp
lib/src/protocol/schemas.cc

Here we add the version_error schema as specified in pcp-specifications.

(PCP-42) Add version_error schema

---

lib/CMakeLists.txt
lib/inc/cpp-pcp-client/util/logging.hpp
lib/src/util/logging.cc

Add a helper to configure logging for cpp-pcp-client.
Required when statically linking Boost.Log.

(PCP-68) Add logging config for cpp-pcp-client

---

CMakeLists.txt

Prior to this changeset, execution of pxp-agent on OS X fails with ```dyld: Library not loaded:
libcpp-pcp-client.so```. To fix this, we borrow from Facter, bumping the cmake requirement to 3.2.2 and setting the CMAKE_INSTALL_RPATH based on the install prefix.

(PCP-67) Bump cmake requirement to 3.2.2, set CMAKE_INSTALL_RPATH

---

lib/inc/cpp-pcp-client/util/logging.hpp
lib/src/util/logging.cc

By default, colorization should be set leatherman::logging, based on
the type of stream (console supports it, since it's based on shell
control sequences, whereas text streams don't). With this commit we call
leatherman's logging::set_colorization(true) only if the user code
wants to force this setting.

(maint) Util::logging forces colorization instead of setting

---

CMakeLists.txt
lib/src/connector/connector.cc

Displaying raw messages before being unserialized on console on Windows
let pxp-agent crash. We define a CMake option to enable such logging,
which is set to OFF by default; such log messages are important during
development.

(PCP-93) Don't log raw messages by default

---

CMakeLists.txt

Leatherman provides defines that enforce Unicode on Windows and correct
handling of UTF-8 in Boost.Log. Use these definitions.

(maint) Use Leatherman defines

---

README.md
lib/src/connector/connection.cc

With this commit we prevent the agent from trying to establish a
WebSocket connection in case the provided TLS certs are not validated by
the boost asio context. This may happen in casse of a cert / key
mismatch or in case of an error when retrieving the password.
Improving log messages.
Improving connect() FSM.

(PCP-125) Error in case fails to validate certs

---

.gitignore
lib/CMakeLists.txt
lib/inc/cpp-pcp-client/connector/client_metadata.hpp
lib/inc/cpp-pcp-client/connector/connection.hpp
lib/inc/cpp-pcp-client/connector/connector.hpp
lib/inc/cpp-pcp-client/protocol/chunks.hpp
lib/inc/cpp-pcp-client/protocol/errors.hpp
lib/inc/cpp-pcp-client/protocol/message.hpp
lib/inc/cpp-pcp-client/protocol/schemas.hpp
lib/inc/cpp-pcp-client/protocol/serialization.hpp
lib/inc/cpp-pcp-client/util/logging.hpp
lib/inc/cpp-pcp-client/validator/schema.hpp
lib/inc/cpp-pcp-client/validator/validator.hpp
lib/tests/CMakeLists.txt

Symbol visibility control can lead to greatly reduced library size on
Windows (all the suepr-long mangled names for C++ types and functions
can become surprisingly large), and also prevents performance
degradation on AIX. Add symbol exporting and annotate symbols that need
to be exported.

(PCP-121) Explicitly export symbols

---

ext/cpp-pcp-client.cmake
lib/CMakeLists.txt
lib/tests/CMakeLists.txt
lib/tests/unit/validator/schema_test.cc

AIX has a limit on shared library TOC size. Try static linking to avoid the issue.
On AIX GCC assumes `-isystem` headers are all C, and will wrap them in `extern "C"`. We were misusing the SYSTEM tag for C++ header files. Stop doing that.

(PCP-136) Use static libraries to resolve AIX linking issues, and don't use SYSTEM

---

lib/tests/CMakeLists.txt

When we were building shared libraries, system libraries were being
included implicitly. Call them out explicitly now for unit tests.

(PCP-136) Fix Solaris dependencies that were implicit

---

lib/inc/cpp-pcp-client/validator/schema.hpp
lib/inc/cpp-pcp-client/valijson/rapidjson_adapter.hpp
lib/src/validator/schema.cc
lib/src/validator/validator.cc
lib/tests/unit/validator/schema_test.cc

Using rapidjson's MemoryPoolAllocator in json_container caused
execution on Solaris SPARC to crash. Update Leatherman to pick up a
fixed version.
This fix requires a new rapidjson adapter for valijson that doesn't use
the MemoryPoolAllocator. Create it locally for now.
Also avoid creating a temporary json_document in the Schema constructor
used for testing, that can lead to freed memory references by valijson.

(PCP-144) Get Leatherman fix for rapidjson and patch valijson

---

lib/CMakeLists.txt
lib/inc/cpp-pcp-client/connector/client_metadata.hpp
lib/inc/cpp-pcp-client/connector/connection.hpp
lib/inc/cpp-pcp-client/connector/connector.hpp
lib/inc/cpp-pcp-client/protocol/chunks.hpp
lib/inc/cpp-pcp-client/protocol/errors.hpp
lib/inc/cpp-pcp-client/protocol/message.hpp
lib/inc/cpp-pcp-client/protocol/schemas.hpp
lib/inc/cpp-pcp-client/protocol/serialization.hpp
lib/inc/cpp-pcp-client/util/logging.hpp
lib/inc/cpp-pcp-client/validator/schema.hpp
lib/inc/cpp-pcp-client/validator/validator.hpp

This reverts commit 5c0a1c887537cd501a348d6c4afd5ca4b4388f48.
I suggest we hold off on this until after the 1st release.

(PCP-121) Explicitly export symbols, again

---

lib/inc/cpp-pcp-client/util/logging.hpp
lib/src/util/logging.cc

Adding an overload of the above function that receives a leatherman's
log_level value instead of a string one.

(maint) Add overload of Util::logging::setupLogging

---

lib/inc/cpp-pcp-client/util/thread.hpp

Adding constant to allow creating unique_lock without acquiring the lock
over a given mutex.

(PCP-172) Add boost::defer_lock_t constant to Util namespace

---

CMakeLists.txt

In the past we defaulted CMAKE_BUILD_TYPE to empty. Here we update the
top level CMakeLists.txt to default to Release.

(PCP-137) Default to Release build

---

CHANGELOG.md
CMakeLists.txt
lib/CMakeLists.txt
lib/inc/cpp-pcp-client/connector/client_metadata.hpp
lib/inc/cpp-pcp-client/connector/connection.hpp
lib/inc/cpp-pcp-client/connector/connector.hpp
lib/inc/cpp-pcp-client/protocol/chunks.hpp
lib/inc/cpp-pcp-client/protocol/errors.hpp
lib/inc/cpp-pcp-client/protocol/message.hpp
lib/inc/cpp-pcp-client/protocol/schemas.hpp
lib/inc/cpp-pcp-client/protocol/serialization.hpp
lib/inc/cpp-pcp-client/util/logging.hpp
lib/inc/cpp-pcp-client/util/thread.hpp
lib/inc/cpp-pcp-client/validator/schema.hpp
lib/inc/cpp-pcp-client/validator/validator.hpp
lib/src/connector/connection.cc
lib/src/util/logging.cc

1.0.2 turned out to be a bad version that we will not be shipping in
puppet-agent.
This reverts commit f39d1371d1717ec7ef1c6c95914c242d121810a8, reversing
changes made to 0a90ea7849630da6c6b1675b0c04477695cdaf42.

Revert "Merge branch 'master' into stable"

---

lib/src/connector/connection.cc

Boost.Asio copied functionality from Boost.System's error_code, but
doesn't copy it in providing a flag to skip it like
BOOST_SYSTEM_NO_DEPRECATED. So ignore unused-variable warnings generated
by Boost.Asio headers.
Due to bug #53431 in GCC 5.2, the warnings will still print, but won't
stop compilation. This may cause issues for AppVeyor when we update GCC.

(maint) Ignore -Wunused-variable in Boost.Asio

---

README.md
lib/inc/cpp-pcp-client/connector/connector.hpp
lib/src/connector/connector.cc

The Connector::send() overloads that create that instantiate Message now
return the id of the created message as a string.
This change is useful to enable the user code to check the in-reply-to
envelope entry when processing response messages sent by a PCP broker.

(PCP-217) Connector::send() returns id when creating msg

---

.gitmodules
.travis.yml
CMakeLists.txt
README.md
appveyor.yml

Removing leatherman's git submodule. Updating CMake, Appveyor, and
Travis configuration scripts. Updating leatherman's dependency on
README.

(PCP-209) Unvendor and rely on installed leatherman

---

CMakeLists.txt
lib/CMakeLists.txt
lib/tests/CMakeLists.txt

Here we add the pthread dependency; it is needed for the linkage of
Boost's date_time (necessary for leatherman_util) in AIX.
This fix relates to [FACT-1338](https://tickets.puppetlabs.com/browse/FACT-1338) and should be removed after [LTH-81](https://tickets.puppetlabs.com/browse/LTH-81).

(PCP-269) Add pthread building dependency

---

lib/CMakeLists.txt

Making an explicit dependency on external projects (websocketpp and
valijson) in order to ensure that they get extracted before
cpp-pcp-client compilation starts, when building with multiple jobs.

(PCP-269) Add dependency to external projects to CMakeLists

---

CMakeLists.txt

cpp-pcp-client uses Boost.Chrono directly, make the requirement
explicit. Previously it picked the dependency up as a side-effect of
using Leatherman, which is fragile when using Leatherman shared
libraries and Boost static libraries.

(maint) Add dependency on Boost.Chrono

---

lib/tests/CMakeLists.txt

Linking pthread was previously put in the wrong place, move it to the
target_link_libraries.

(maint) Fix building test on AIX

---

lib/CMakeLists.txt
lib/inc/cpp-pcp-client/connector/connector.hpp
lib/inc/cpp-pcp-client/connector/errors.hpp
lib/inc/cpp-pcp-client/connector/session_association.hpp
lib/src/connector/connection.cc
lib/src/connector/connector.cc
lib/src/connector/session_association.cc

- Style changes
- Improvements for log messages
- Associate Session:
Performing Associate Session only after Connection::connect() returns.
Terminating pxp-agent in case of an Associate Session failure.
Considering possible corrupted messages and PCP Errors during the
Session Association phase.
Considering a timeout when waiting for the Session Association outcome.
Blocking the associateSession() callback, triggered by the onOpen
handler, until Connection::connect() return, in order to avoid a data
race with the Connection's FSM in case of Associate Session failure.
Refactoring Session Association state attributes in a new class.
Defining new errors.
The Monitor Task will attempt to reconnect in case of a corrupted error
or timeout during Session Association.

(PCP-338) New logic for Associate Session

---

lib/tests/main.cc
lib/tests/unit/connector/connection_test.cc

An unit test for the Connection class used to pause for 5 s due to the
cleanup() method being invoked by default; this commit reduces such
pause to 6 ms.
Also we introduce a macro to enable logging for unit tests, as done in
pxp-agent.

(maint) Remove unnecessary pause from Connection test

---

lib/tests/main.cc

Removing the Catch's applyCommandLine() and passing CLI arguments
directly to the Session::run() function; note that setting ConfigData
showDurations to "Always" works in the same way as it's not changed by
our CI pipeline via CLI.

(maint) Make tests compatible with leatherman 0.4 and 0.5

---

lib/CMakeLists.txt
lib/tests/CMakeLists.txt

Fix Leatherman and Boost library order so we can build with shared Leatherman libraries on Windows.

(PCP-372) Support building with Leatherman DLLs

---

CMakeLists.txt
lib/CMakeLists.txt

Configure the cpp-pcp-client library so we can use a CMake option to
declare whether it will be built as a static or shared library. Default
to shared.

(maint) Make static/shared libraries toggleable

---

CMakeLists.txt
lib/CMakeLists.txt
lib/tests/CMakeLists.txt

Fixes in Leatherman made explicit pthread dependencies unnecessary.
Remove them.

(PCP-270) Remove outsourced pthread dependency

---

CMakeLists.txt
lib/CMakeLists.txt
lib/tests/CMakeLists.txt

Reverts puppetlabs/cpp-pcp-client#157
Still required on AIX.

Revert "(PCP-270) Remove outsourced pthread dependency"

---

.gitignore
CMakeLists.txt
lib/inc/cpp-pcp-client/connector/timings.hpp
lib/inc/cpp-pcp-client/protocol/serialization.hpp
lib/src/connector/client_metadata.cc
lib/src/connector/connection.cc
lib/src/connector/connector.cc
lib/src/connector/timings.cc
lib/src/protocol/message.cc
lib/src/protocol/serialization.cc
lib/src/validator/schema.cc
lib/src/validator/validator.cc
locales/cpp-pcp-client.pot

Enable the creation of the .pot file that includes the strings that
we want to translate. Don't enable localization now; we'll do that on
PCP-257.
Use leatherman::locale::format() and translate() for the strings that we
want to translate.
Use "{<int>}" instead of "%<int>%" for string interpolation.
Don't use leatherman::util::plural(); we'll deal with plurals once we
enable localization on PCP-257.

(PCP-371) Spike i18n

---

CMakeLists.txt
lib/CMakeLists.txt
lib/tests/CMakeLists.txt

AIX linking requires declaring the dependency on pthreads explicitly.

(maint) Update comments noting that AIX requires threads

---

appveyor.yml

AppVeyor images were updated to include software that installs OpenSSL
binaries to `C:\Windows\System32`.
https://msdn.microsoft.com/en-us/library/7d83bc18.aspx describes the
Windows search path, which puts the Windows system directory before
PATH. The easiest way to ensure the libraries are loaded earlier is to
put them in the same directory as the test executable, so do that.

(maint) Fix AppVeyor builds

---

README.md
lib/inc/cpp-pcp-client/connector/client_metadata.hpp
lib/inc/cpp-pcp-client/connector/connector.hpp
lib/src/connector/client_metadata.cc
lib/src/connector/connector.cc
lib/tests/unit/protocol/serialization_test.cc

This reverts commit 1ea5c3a8a15ba9a7ff78ed131892ab4e7439fcdf.
`long` is used for a websocketpp API that expects a long. Avoid compile
errors on 32-bit platforms and Windows (they may not happen everywhere,
because GCC doesn't give conversion warnings with our config).

Revert "(maint) Ban long integers"

---

lib/src/connector/connection.cc
lib/src/connector/connector.cc
lib/src/protocol/message.cc
locales/cpp-pcp-client.pot

Until Leatherman adds plural i18n helpers, we don't want a release to
backtrack on pluralizing message strings. Restore basic pluralization in
a way similar to what the i18n helpers will do.

(maint) Restore plural messages

---

lib/src/connector/connection.cc

The lack of `no_sslv3` doesn't affect initiating a connection, it only
controls what connections will be accepted by an asio server (hence not
a security issue in cpp-pcp-client). However, since we specify
`no_sslv2` it seems clearer to also specify `no_sslv3` to be
unambiguous.

(maint) Add no_sslv3 to avoid ambiguity around protocols

---

lib/tests/unit/connector/connection_test.cc

Increase connection timeout to allow more time for connections to be
made on test hardware.

(maint) Extend timeout for unit test to associate

---

lib/tests/CMakeLists.txt

`mock_server.cc` contains an unrecognized dependency on `websocketpp`.
This can cause parallel builds to fail by trying to compile
`mock_server.cc` before `websocketpp` has been unpacked. Fix by adding
an explicit dependency between `websocketpp` and the `mock-server`
target.

(maint) Add missing dependency for mock-server

---

lib/inc/cpp-pcp-client/connector/connection.hpp
lib/src/connector/connection.cc

Updates to compare target URI strings, rather than their positions in
the URI list. Also prints out the URIs themselves rather than numbers.

(PCP-412) Update message to print target strings instead of numbers

---

lib/src/connector/connection.cc
lib/tests/unit/connector/connection_test.cc
locales/cpp-pcp-client.pot

Previous to this commit, the connectAndWait method was returning
immediately in case the WS connection timeout was set to a value lesser
than 1 s; here we fix this.
Adding unit tests to check that the dtor does not hang in case the
configured WebSocket connection timeout is ~ 1 ms.

(PCP-424) Connection must not return before connection_timeout

---

lib/inc/cpp-pcp-client/connector/connection.hpp
lib/src/connector/connection.cc
lib/tests/unit/connector/connection_test.cc

Setting the connection state to closing in Connection::close(); using a
mutex to handle the connection state.
Improving the logic for checking the connection state when the
Connection::clean() is invoked (ex. by the dtor): wait in case the
connection state is connecting or closing. Note that the underlying
websocketpp won't close the connection if the WebSocket onOpen event has
not being triggered.

(PCP-425) Wait before closing connection if connecting

---

lib/inc/cpp-pcp-client/connector/client_metadata.hpp
lib/inc/cpp-pcp-client/connector/connector.hpp
lib/src/connector/client_metadata.cc
lib/src/connector/connection.cc
lib/src/connector/connector.cc
lib/tests/unit/connector/client_metadata_test.cc
lib/tests/unit/connector/connection_test.cc
locales/cpp-pcp-client.pot

If several consecutive pong responses to pings time out - the number is
configurable - the connection will be closed. This allows fail over to
other brokers if the connected broker becomes unresponsive. Otherwise
the client would never attempt to disconnect from an unresponsive
broker.
P.S. I'm not really sure how to unit test this type of dropped connection.

(PCP-423) Close unresponsive connections

---

lib/inc/cpp-pcp-client/connector/connector.hpp
lib/src/connector/connector.cc
locales/cpp-pcp-client.pot

The method that starts the monitoring task now spawns a new thread and
returns immediately; it is up to the user code to pause its execution
thread.
Adding a new method to Connector for stopping the monitoring thread.

(PCP-454) Make Connector::startMonitoring non blocking

---

lib/inc/cpp-pcp-client/connector/client_metadata.hpp
lib/inc/cpp-pcp-client/connector/connector.hpp
lib/src/connector/client_metadata.cc
lib/src/connector/connector.cc
lib/tests/unit/connector/client_metadata_test.cc
lib/tests/unit/connector/connection_test.cc

Allow configuring the overall timeout for the Association process in
addition to the Association request ttl.

(PCP-452) Configure timeout for whole Association process

---

lib/CMakeLists.txt
lib/inc/cpp-pcp-client/connector/connector.hpp
lib/inc/cpp-pcp-client/protocol/schemas.hpp
lib/src/connector/connection.cc
lib/src/connector/connector.cc
lib/tests/CMakeLists.txt
lib/tests/unit/connector/connector_test.cc
lib/tests/unit/connector/mock_server.cc
lib/tests/unit/connector/mock_server.hpp
locales/cpp-pcp-client.pot

Adding new functionalities for the MockServer:
- configurable handler for WebSocket pings;
- Association Request handler (triggered by onMessage event).
The connection_check interval of Connector::startMonitoring is now an
argument of the method; this allows us to write unit tests with a
monitor task that has a very short period.
Adding new connector_test.cc with unit tests for Connector::connect and
Connector::startMonitoring (to ensure it reconnects when the broker goes
down and that the connection gets closed after a number of pong timeouts).

(PCP-455) Connector unit tests

---

lib/inc/cpp-pcp-client/connector/client_metadata.hpp
lib/inc/cpp-pcp-client/connector/connector.hpp
lib/src/connector/connector.cc
lib/tests/unit/connector/client_metadata_test.cc
lib/tests/unit/connector/connection_test.cc
lib/tests/unit/connector/connector_test.cc
locales/cpp-pcp-client.pot

- Removing default value for pong timeout from ClientMetadata ctor
- Refactoring Connector's unit tests
- New unit tests for storing/rethrowing Monitor Thread exceptions
- Rethrowing Monitor Thread exceptions after its completion

(PCP-463) Unit tests and improvements for Monitor errors

---

lib/inc/cpp-pcp-client/connector/connection.hpp
lib/inc/cpp-pcp-client/connector/connector.hpp
lib/inc/cpp-pcp-client/connector/timings.hpp
lib/src/connector/connection.cc
lib/src/connector/connector.cc
lib/src/connector/timings.cc
lib/tests/unit/connector/connection_test.cc
lib/tests/unit/connector/connector_test.cc
locales/cpp-pcp-client.pot

Style changes.
Adding new AssociationTimings struct, to keep track of the time spent
for associating and the entire session duration.
Adding AssociationTimings member to Connector.
Adding methods to set onClose and onFail callbacks to Connection.
Resetting and updating AssociationTimings in Connector's onOpen callback
(the one that sends that Associate request) and in the connect() synch
method.
Adding AssociationTimings getter to Connector.
Adding AssociationTimings unit tests to connector_test.

(PCP-411) Retrieve and expose PCP Association timings

---

lib/inc/cpp-pcp-client/connector/timings.hpp
lib/src/connector/connection.cc
lib/src/connector/timings.cc
lib/tests/main.cc
lib/tests/test.hpp
lib/tests/unit/connector/connection_test.cc
lib/tests/unit/connector/connector_test.cc
lib/tests/unit/connector/mock_server.cc
locales/cpp-pcp-client.pot

Making the websocketpp logging for MockServer optional, 
as done for PCP logging within unit tests.
Macros are now listed in tests/test.hpp.
Retrieving WS Closing Handshake timings if the close() synch method was
triggered by the client endpoint. Adding logic for doing that in
ConnectionTimings.
Making state flags of ConnectionTimings private and adding getters.
Adding new unit tests for the ConnectionTimings changes.
Don't log error when onClose's code is 1000 (normal).

(PCP-440) MockServer logging and WS Closing Handshake

---

.travis_target.sh
lib/inc/cpp-pcp-client/connector/connection.hpp
lib/src/connector/connection.cc
lib/tests/unit/connector/connection_test.cc
lib/tests/unit/connector/mock_server.cc
lib/tests/unit/connector/mock_server.hpp

Here we introduce concurrency logic to synchronize onOpen events
between the onOpen handler and the synchronous connectAndWait blocking
call. Such logic replaces the old check and wait loop based of 200 ms
period and allows returning as soon as the onOpen event is triggered and
prevents further delays when performing the Session association.
Updating unit tests. That requires exposing MockServer's tcp_pre_init
handler to allow introducing a delay for  establishing the WebSocket
connection. Also introducing a 20 ms pause before checking if the onOpen
handler in the MockServer instance was called, after the client's
connect() call returned.
Also updating the gettext version used by Travis.

(PCP-477) Check connection by synchronizing onOpen events

---

lib/tests/unit/connector/connection_test.cc
lib/tests/unit/connector/mock_server.cc
lib/tests/unit/connector/mock_server.hpp

Here we use the validate handler to introduce delays for establishing
the WebSocket connection when testing.

(maint) Use validate handler to delay MockServer

---

lib/inc/cpp-pcp-client/connector/connector.hpp
lib/src/connector/connector.cc
lib/tests/unit/connector/connector_test.cc
locales/cpp-pcp-client.pot

Resets default pong timeout to 5 seconds, and throws an exception when
connection check is shorter than pong timeout (which prevents timeout
from occurring).

(PCP-499) Ensure pong timeout is shorter than connection check

---

lib/src/connector/connection.cc
locales/cpp-pcp-client.pot

Adds ca mismatch as a possible reason that SSL verification could fail.

(PCP-543) Add ca mismatch as possible failure cause

---

lib/inc/cpp-pcp-client/connector/connection.hpp
lib/inc/cpp-pcp-client/util/logging.hpp
lib/src/connector/connector.cc
lib/src/util/logging.cc
locales/cpp-pcp-client.pot

The WS URI of the broker that pxp-agent is connected to is needed for
logging PCP access; here we make the relevant Connector's method public.
Adding an ad-hoc sink backend that format log messages in a simplified
way, compared to leatherman's logging.
Configuring a new boost log sink with a filter specific for PCP access
logging.
Adding PCP access logger and exposing a logging macro, similar to what
leatherman.logging does.
Logging PCP access from the onMessage callback.

(PCP-556) PCP access logging

---

lib/inc/cpp-pcp-client/connector/connector.hpp
lib/inc/cpp-pcp-client/util/thread.hpp
lib/src/connector/connector.cc

On some ARM architectures, GCC doesn't support std::exception_ptr. Use
boost's instead (which requires some tweaking).

(PCP-582) Use boost::exception_ptr

---

lib/inc/cpp-pcp-client/util/logging.hpp
lib/src/util/logging.cc

Using boost::nowide::ofstream for the access logging stream.

(maint) Use boost.nowide stream for access logging

---

lib/src/util/logging.cc

In Boost 1.62, the way sink argument forwarding appears to have changed
in such a way that it failed to identify the implicit creation of a
access_writer. Switch to explicitly creating the access_writer sink.

(PCP-617) Fix Boost.Log sink initialization with Boost 1.62

---

lib/src/connector/v2/connector.cc
lib/tests/unit/connector/mock_server.cc
lib/tests/unit/connector/mock_server.hpp
lib/tests/unit/connector/v2/connector_test.cc

The prior commits adding PCP version 2 didn't append the client_type to
connection URIs, expecting that users would do it themselves. Since
client_type is already an argument, use it to modify the connection URIs
to match broker expectations.

(PCP-679) Append client_type to connection URIs

---

lib/src/connector/connection.cc
lib/tests/unit/connector/mock_server.cc

Previously boost.asio was configured to use TLS v1.0. This actually
prevented working with clients that only support TLS v1.1 or later. Use
TLS v1.2 instead.
Note that this only attempts to make TLS v1.2 connections, and will not
attempt any other type.

(PCP-719) Use TLS v1.2

---

lib/src/connector/connector_base.cc

In large scale environments, nodes occasionally fail with unknown
exceptions. Add logging for when that happens.

(maint) Log unknown exceptions

---

lib/inc/cpp-pcp-client/connector/connector_base.hpp
lib/src/connector/connector_base.cc
lib/src/connector/v1/connector.cc

Previously failed connections would only be detected on the
ping-interval. Notify of disconnects immediately, with a 200ms delay
before attempting to reconnect to avoid busy waiting against pcp-broker.

(PCP-734) Detect closed connection immediately and attempt reconnect

---

lib/src/connector/connector_base.cc

A `connection_processing_error` can be sent during `send`/`ping`/`close`
if the connection closes during the operation. We should catch and try
re-establishing a connection when that happens.

(PCP-715) Continue after processing error

---

lib/src/connector/connection.cc

Previously the retry logic would always retry connections within 250ms
of 2, 4, 6, etc. This is insufficient to prevent a thundering herd when
large numbers of agents are involved. This change carries randomization
from the nth iteration into the n+1th, which should increase the
divergence between agents as number of retries increases.

(PCP-738) increase randomization of PCP connection retry

---

lib/inc/cpp-pcp-client/util/thread.hpp

In preparing puppet-agent for boost 1.67 (https://github.com/puppetlabs/puppet-agent/pull/1482), we found that a 1.67 thread header defines an an unused variable on Windows under mingw; This ignores the warning so that it doesn't fail the build while using -Werror.

(PA-2055) Quiet boost 1.67 warnings on windows

---

lib/src/connector/connection.cc

Making this build under gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
/home/rroland/src/cpp-pcp-client/lib/src/connector/connection.cc: In member function ‘void PCPClient::Connection::cleanUp()’:
/home/rroland/src/cpp-pcp-client/lib/src/connector/connection.cc:350:21: error: this statement may fall through [-Werror=implicit-fallthrough=]
tryClose();
~~~~~~~~^~
/home/rroland/src/cpp-pcp-client/lib/src/connector/connection.cc:351:9: note: here
case (ConnectionState::closing):
^~~~

(maint) making this build under gcc 7.5.0

---

README.md
lib/inc/cpp-pcp-client/protocol/v1/serialization.hpp
lib/src/protocol/v1/serialization.cc

The boost/detail/endian.hpp header is deprecated.
Here is the warning that was coming from the serialization file:
```
In file included from /usr/local/include/cpp-pcp-client/protocol/v1/serialization.hpp:8:
In file included from /usr/local/include/boost/detail/endian.hpp:9:
/usr/local/include/boost/predef/detail/endian_compat.h:11:9: warning: The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead [-W#pragma-messages]
#pragma message("The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead")
^
1 warning generated.
```

(maint) Fix Endian warning in Serialization

---

lib/src/protocol/v1/serialization.cc

In a previous commit [1], ifdef was incorrectly changed
to if in the serialization protocol. This commit corrects
that.
[1]: https://github.com/puppetlabs/cpp-pcp-client/commit/36ec2eba1ee6c0edeaaaaad9836041f84a02e463#diff-03a0c044596526965eba33d65a5657dbR12

(maint) if -> ifdef in serialization protocol

---

lib/inc/cpp-pcp-client/connector/connection.hpp
lib/src/connector/connection.cc

There is an undiagnosed bug around websocket logging on Windows, so
temporarily disable that logging until a solution can be found.
This restores the use of the default ASIO TLS client config, rather than
our custom config which enables devel logging. It also explicitly sets
the websocket log level to none and doesn't set a stream.

(PE-33165) Disable websocket logging
